armq admin wrapper

diff --git a/armq_admin b/armq_admin
--- a/armq_admin
+++ b/armq_admin
@@ -1,2 +1,6 @@
 #!/bin/bash
-armq_server --mode admin --command $1
+if [ -z "$1" ]; then
+    echo "command required"
+    exit 1
+fi
+armq_server --mode admin --command $@
